version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 7000:7000
    depends_on:
      - redis-service
    networks:
      - medscroll_network

  redis-service:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - medscroll_network

networks:
  medscroll_network:
    driver: bridge
