export enum CaseType {
  LONG_CASE = 'LONG_CASE',
  SHORT_CASE = 'SHORT_CASE',
}

export enum ClinicalExamPromptType {
  EXAMINAL_1 = 'EXAMINAL_1',
  EXAMINAL_2 = 'EXAMINAL_2',
  AI_GRADING = 'AI_GRADING',
  AI_GRADING_SC = 'AI_GRADING_SC',
  AI_GRADING_LC = 'AI_GRADING_LC',
  NEXT_QUESTION = 'NEXT_QUESTION',
  AI_FEEDBACK_SC = 'AI_FEEDBACK_SC',
  AI_FEEDBACK_LC = 'AI_FEEDBACK_LC',
  START_EXAMINALS = 'START_EXAMINALS',
  START_EXAM_BOT_SC = 'START_EXAM_BOT_SC',
  START_EXAM_BOT_LC = 'START_EXAM_BOT_LC',
  START_PRESENTATION = 'START_PRESENTATION',
  SUBMIT_PRESENTATION = 'SUBMIT_PRESENTATION',
  START_PRACTICE_CASE = 'START_PRACTICE_CASE',
  START_PATIENT_EXAMINATION = 'START_PATIENT_EXAMINATION',
}

export enum GenderType {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum TutorialStatus {
  NOT_STARTED = 'Not Started',
  IN_PROGRESS = 'Ongoing',
  COMPLETED = 'Completed',
}

export enum TutorialQuizType {
  MULTIPLE_CHOICE = 'MULTICHOICE',
  TRUE_FALSE = 'TRUE FALSE',
  OPEN_ENDED = 'OPEN ENDED QUESTION',
}

export enum TemplateCaseType {
  LONG_CASE = 'LONG CASE',
  SHORT_CASE = 'SHORT CASE',
}
